name: NPM Packages CI

on:
  workflow_call:
    secrets:
      ORG_REPO_TOKEN:
        required: true

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ORG_REPO_TOKEN }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.14.0
          cache: yarn

      - name: Setup Environment
        run: bash scripts/setup.sh

      - name: Check Changelogs Compliance
        run: bash scripts/check-changelogs.sh

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint Packages
        run: yarn lint

      - name: Build Packages
        run: yarn build

      - name: Test Packages
        run: yarn test
